import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Team, Player, Match } from '../types/cricket';

export const generateTeamPDF = async (team: Team, tournamentName: string = 'Apna Cricket', match?: any) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Branding Colors
  const brandRed = '#E11D48';
  const slate900 = '#0F172A';
  const slate400 = '#94A3B8';

  // Header - Apna Cricket Branding
  doc.setFillColor(slate900);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('APNA CRICKET', 20, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(225, 29, 72); // brandRed
  doc.text('OFFICIAL TEAM SHEET', 20, 32);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text(tournamentName.toUpperCase(), pageWidth - 20, 25, { align: 'right' });

  // Team Name Section
  doc.setTextColor(slate900);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text(team.name.toUpperCase(), 20, 60);
  
  // Decorative line
  doc.setDrawColor(225, 29, 72);
  doc.setLineWidth(2);
  doc.line(20, 65, 60, 65);

  // Toss Info
  if (match) {
    doc.setTextColor(slate400);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    const tossText = match.tossWinnerId === team.id 
      ? `TOSS WON: ELECTED TO ${match.tossDecision.toUpperCase()}`
      : `TOSS LOST: OPPONENT ELECTED TO ${match.tossDecision.toUpperCase()}`;
    doc.text(tossText, 20, 72);
  }

  // Captain Section
  const captain = team.players.find(p => p.isCaptain) || team.players[0];
  
  doc.setFillColor(248, 250, 252); // slate-50
  doc.roundedRect(20, 75, pageWidth - 40, 30, 5, 5, 'F');
  
  // Captain Icon Placeholder (Circle)
  doc.setFillColor(225, 29, 72);
  doc.circle(35, 90, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('C', 35, 91, { align: 'center' });
  
  doc.setTextColor(slate900);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(captain.name.toUpperCase(), 50, 88);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(slate400);
  doc.text('TEAM CAPTAIN', 50, 94);

  // Players List
  doc.setTextColor(slate900);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('SQUAD LINEUP', 20, 120);
  
  let y = 130;
  team.players.forEach((player, index) => {
    // Alternate background for rows
    if (index % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(20, y - 6, pageWidth - 40, 10, 'F');
    }
    
    doc.setTextColor(slate900);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}.`, 25, y);
    doc.text(player.name.toUpperCase(), 35, y);
    
    doc.setTextColor(slate400);
    doc.setFont('helvetica', 'normal');
    doc.text(player.role.toUpperCase(), pageWidth - 25, y, { align: 'right' });
    
    y += 10;
    
    // Add new page if needed
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(slate400);
  const footerText = `Generated by Apna Cricket • ${new Date().toLocaleDateString()} • Keep it Real.`;
  doc.text(footerText, pageWidth / 2, 285, { align: 'center' });

  doc.save(`${team.name}_TeamSheet.pdf`);
};

export const generatePlayerPDF = async (player: { id: string; name: string }, stats: any) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  const brandRed = '#E11D48';
  const slate900 = '#0F172A';
  const slate400 = '#94A3B8';

  // Header
  doc.setFillColor(slate900);
  doc.rect(0, 0, pageWidth, 50, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.text('APNA CRICKET', 20, 20);
  
  doc.setFontSize(8);
  doc.setTextColor(brandRed);
  doc.text('PLAYER PERFORMANCE VERIFIED', 20, 26);

  // Player Name
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(36);
  doc.setFont('helvetica', 'bold');
  doc.text(player.name.toUpperCase(), 20, 42);

  // Batting Stats Section
  doc.setTextColor(slate900);
  doc.setFontSize(14);
  doc.text('BATTING CAREER', 20, 70);
  doc.setDrawColor(brandRed);
  doc.setLineWidth(1);
  doc.line(20, 72, 40, 72);

  const battingStats = [
    { label: 'MATCHES', value: stats.batting.matches },
    { label: 'TOTAL RUNS', value: stats.batting.runs },
    { label: 'HIGHEST', value: stats.batting.highestScore },
    { label: 'AVERAGE', value: stats.batting.matches > 0 ? (stats.batting.runs / (stats.batting.matches - stats.batting.notOuts || 1)).toFixed(1) : '0.0' },
    { label: 'STRIKE RATE', value: stats.batting.balls > 0 ? ((stats.batting.runs / stats.batting.balls) * 100).toFixed(1) : '0.0' },
    { label: '4s / 6s', value: `${stats.batting.fours} / ${stats.batting.sixes}` }
  ];

  let y = 85;
  battingStats.forEach((stat, i) => {
    const x = i % 2 === 0 ? 20 : pageWidth / 2 + 5;
    const currentY = i % 2 === 0 ? y : y;
    
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, currentY, (pageWidth / 2) - 25, 20, 3, 3, 'F');
    
    doc.setTextColor(slate400);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(stat.label, x + 5, currentY + 7);
    
    doc.setTextColor(slate900);
    doc.setFontSize(12);
    doc.text(stat.value.toString(), x + 5, currentY + 15);
    
    if (i % 2 !== 0) y += 25;
  });

  // Bowling Stats Section
  y += 10;
  doc.setTextColor(slate900);
  doc.setFontSize(14);
  doc.text('BOWLING CAREER', 20, y);
  doc.line(20, y + 2, 40, y + 2);
  y += 15;

  const bowlingStats = [
    { label: 'INNINGS', value: stats.bowling.innings },
    { label: 'WICKETS', value: stats.bowling.wickets },
    { label: 'BEST', value: `${stats.bowling.bestBowling.wickets}/${stats.bowling.bestBowling.runs}` },
    { label: 'ECONOMY', value: stats.bowling.overs > 0 ? (stats.bowling.runs / (stats.bowling.overs + stats.bowling.balls/6)).toFixed(2) : '0.00' },
    { label: 'MAIDENS', value: stats.bowling.maidens },
    { label: 'TOTAL RUNS', value: stats.bowling.runs }
  ];

  bowlingStats.forEach((stat, i) => {
    const x = i % 2 === 0 ? 20 : pageWidth / 2 + 5;
    const currentY = i % 2 === 0 ? y : y;
    
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(x, currentY, (pageWidth / 2) - 25, 20, 3, 3, 'F');
    
    doc.setTextColor(slate400);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'bold');
    doc.text(stat.label, x + 5, currentY + 7);
    
    doc.setTextColor(slate900);
    doc.setFontSize(12);
    doc.text(stat.value.toString(), x + 5, currentY + 15);
    
    if (i % 2 !== 0) y += 25;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(slate400);
  const footerText = `Official Career Profile • Generated by Apna Cricket • ${new Date().toLocaleDateString()}`;
  doc.text(footerText, pageWidth / 2, 285, { align: 'center' });

  doc.save(`${player.name}_Profile.pdf`);
};

export const generateFixturesPDF = async (tournamentName: string, matches: Match[]) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  const brandRed = '#E11D48';
  const slate900 = '#0F172A';
  const slate400 = '#94A3B8';

  // Header
  doc.setFillColor(slate900);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('APNA CRICKET', 20, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(brandRed);
  doc.text('OFFICIAL TOURNAMENT FIXTURES', 20, 32);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text(tournamentName.toUpperCase(), pageWidth - 20, 25, { align: 'right' });

  // Title
  doc.setTextColor(slate900);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('MATCH SCHEDULE', 20, 55);
  
  doc.setDrawColor(brandRed);
  doc.setLineWidth(1);
  doc.line(20, 58, 50, 58);

  let y = 70;
  matches.forEach((match, index) => {
    // Match Card
    doc.setFillColor(248, 250, 252);
    doc.roundedRect(20, y, pageWidth - 40, 35, 3, 3, 'F');
    
    // Match Number & Status
    doc.setTextColor(slate400);
    doc.setFontSize(8);
    doc.text(`MATCH ${index + 1}`, 25, y + 8);
    
    doc.setTextColor(brandRed);
    doc.setFontSize(8);
    doc.text(match.status.toUpperCase(), pageWidth - 25, y + 8, { align: 'right' });

    // Teams
    doc.setTextColor(slate900);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    
    const teamA = match.teamAName.toUpperCase();
    const teamB = match.teamBName.toUpperCase();
    
    doc.text(teamA, 25, y + 20);
    doc.setTextColor(slate400);
    doc.setFontSize(10);
    doc.text('VS', pageWidth / 2, y + 20, { align: 'center' });
    doc.setTextColor(slate900);
    doc.setFontSize(14);
    doc.text(teamB, pageWidth - 25, y + 20, { align: 'right' });

    // Date & Time
    doc.setTextColor(slate400);
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    const dateStr = match.matchDate ? `DATE: ${match.matchDate}` : 'DATE: TBD';
    const timeStr = match.matchTime ? `TIME: ${match.matchTime}` : 'TIME: TBD';
    doc.text(`${dateStr}  |  ${timeStr}`, 25, y + 30);
    
    if (match.umpireName) {
      doc.text(`UMPIRE: ${match.umpireName.toUpperCase()}`, pageWidth - 25, y + 30, { align: 'right' });
    }

    y += 45;

    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(slate400);
  const footerText = `Generated by Apna Cricket • ${new Date().toLocaleDateString()} • apnacricket.co.in`;
  doc.text(footerText, pageWidth / 2, 285, { align: 'center' });

  doc.save(`${tournamentName.replace(/\s+/g, '_')}_Fixtures.pdf`);
};
