import { jsPDF } from 'jspdf';
import html2canvas from 'html2canvas';
import { Team, Player } from '../types/cricket';

export const generateTeamPDF = async (team: Team, tournamentName: string = 'Apna Cricket', match?: any) => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Branding Colors
  const brandRed = '#E11D48';
  const slate900 = '#0F172A';
  const slate400 = '#94A3B8';

  // Header - Apna Cricket Branding
  doc.setFillColor(slate900);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(24);
  doc.text('APNA CRICKET', 20, 25);
  
  doc.setFontSize(10);
  doc.setTextColor(225, 29, 72); // brandRed
  doc.text('OFFICIAL TEAM SHEET', 20, 32);
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(12);
  doc.text(tournamentName.toUpperCase(), pageWidth - 20, 25, { align: 'right' });

  // Team Name Section
  doc.setTextColor(slate900);
  doc.setFontSize(32);
  doc.setFont('helvetica', 'bold');
  doc.text(team.name.toUpperCase(), 20, 60);
  
  // Decorative line
  doc.setDrawColor(225, 29, 72);
  doc.setLineWidth(2);
  doc.line(20, 65, 60, 65);

  // Toss Info
  if (match) {
    doc.setTextColor(slate400);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    const tossText = match.tossWinnerId === team.id 
      ? `TOSS WON: ELECTED TO ${match.tossDecision.toUpperCase()}`
      : `TOSS LOST: OPPONENT ELECTED TO ${match.tossDecision.toUpperCase()}`;
    doc.text(tossText, 20, 72);
  }

  // Captain Section
  const captain = team.players.find(p => p.isCaptain) || team.players[0];
  
  doc.setFillColor(248, 250, 252); // slate-50
  doc.roundedRect(20, 75, pageWidth - 40, 30, 5, 5, 'F');
  
  // Captain Icon Placeholder (Circle)
  doc.setFillColor(225, 29, 72);
  doc.circle(35, 90, 8, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('C', 35, 91, { align: 'center' });
  
  doc.setTextColor(slate900);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(captain.name.toUpperCase(), 50, 88);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(slate400);
  doc.text('TEAM CAPTAIN', 50, 94);

  // Players List
  doc.setTextColor(slate900);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('SQUAD LINEUP', 20, 120);
  
  let y = 130;
  team.players.forEach((player, index) => {
    // Alternate background for rows
    if (index % 2 === 0) {
      doc.setFillColor(248, 250, 252);
      doc.rect(20, y - 6, pageWidth - 40, 10, 'F');
    }
    
    doc.setTextColor(slate900);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(`${index + 1}.`, 25, y);
    doc.text(player.name.toUpperCase(), 35, y);
    
    doc.setTextColor(slate400);
    doc.setFont('helvetica', 'normal');
    doc.text(player.role.toUpperCase(), pageWidth - 25, y, { align: 'right' });
    
    y += 10;
    
    // Add new page if needed
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(slate400);
  const footerText = `Generated by Apna Cricket • ${new Date().toLocaleDateString()} • Keep it Real.`;
  doc.text(footerText, pageWidth / 2, 285, { align: 'center' });

  doc.save(`${team.name}_TeamSheet.pdf`);
};
